export const ACTIONS = {
  LOAD_CURRENT_CORRESPONDENCE: 'LOAD_CURRENT_CORRESPONDENCE',
  LOAD_CORRESPONDENCES: 'LOAD_CORRESPONDENCES',
  SAVE_CHECKBOX_STATE: 'SAVE_CHECKBOX_STATE',
  CLEAR_CHECKBOX_STATE: 'CLEAR_CHECKBOX_STATE'
};
